### ISSUE TITLE
Filter op vak

### ISSUE THREAD

**Issue by decommentator** [sikkepitje/TeamSync#3]
Is het ook mogelijk om te filteren op vak?
Dus bijv het vak examenleerling eruit te houden?

**Comment by sikkepitje** [comment]
Nee, filteren op vak is nog niet mogelijk. Het lijkt mij wel een nuttige toevoeging overigens. Als ik binnenkort tijd heb, zal ik deze functionaliteit toevoegen.

**Comment by sikkepitje** [comment]
Het is met de laatste update 20210803 mogelijk om te filteren op teamnaam. Daarmee is het ook mogelijk om te filteren op vak. Ik sluit daarom deze issue.
